baseurl      = "joaofonseca.dev"
title        = "João Fonseca // Software Developer"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Lisbon-based game engines and C++ enthusiast, constantly juggling too many side projects and wondering where all the time goes."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Lisbon based developer with too many side projects and not enough time"
  keywords = ""
  images = [""]

  justifyContent = true

  [params.meta]
    favicon = true

  [params.author]
    name = "João Fonseca"

  [params.logo]
    logoMark     = "//"
    logoText     = "João Fonseca"
    logoHomeLink = "/"
    # logoCursorDisabled = false
    logoCursorColor    = "#d84a4a"
    logoCursorAnimate  = "1s"
    # logoCursorPathname = true

  [params.footer]
    trademark = "2022 - 2024 • João Fonseca"
    rss = false
    copyright = false
    author = false

  [[params.social]]
    name = "email"
    url  = "mailto:hello@joaofonseca.dev"

  [[params.social]]
    name = "X"
    url  = "https://x.com/joaofonsecadev"

  [[params.social]]
    name = "github"
    url  = "https://github.com/joaofonsecadev"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/joaofonsecadev/"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume"
